apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      initContainers:
        - name: init-db
          image: postgres:12
          envFrom:
          - secretRef:
              name: postgres-secret
          command: ["sh", "-c", "until pg_isready -U $POSTGRES_USER -d $POSTGRES_DB; do echo waiting for database; sleep 2; done"]
      containers:
      - name: postgres
        image: postgres:12
        envFrom:
        - secretRef:
            name: postgres-secret
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data
        ports:
        - containerPort: 5432
        readinessProbe:
          exec:
            command: ["pg_isready", "-U", "myuser", "-d", "mydatabase"]
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: pgdata
        emptyDir: {}
