version: '3.8'

services:
  init_db:
    image: postgres:12
    container_name: init_db_container
    env_file: 
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: ["postgres", "-c", "fsync=off"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: postgres:12
    container_name: postgres_container
    env_file: 
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    depends_on:
      init_db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5

  jupyterlab:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jupyterlab_container
    volumes:
      - .:/workspace
      - /app/data
    ports:
      - "${JUPYTER_PORT}:8888"
    depends_on:
      - db
    command: ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--NotebookApp.token=${JUPYTER_TOKEN}"]
    environment:
      - JUPYTER_TOKEN=${JUPYTER_TOKEN}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${JUPYTER_PORT}/"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  pgdata:

networks:
  default:
    name: my_network
